### ISSUE TITLE
Error after running :  bundle exec jekyll serve

### ISSUE THREAD

**Issue by shmuhammad2004** [zerostaticthemes/jekyll-serif-theme#68]
Hi,

Thank you for the good work. 

I tried to run  `bundle exec jekyll serve` but it is giving me an erro below:

```


bundler: failed to load command: jekyll (/Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/bin/jekyll)
LoadError: cannot load such file -- google/protobuf_c
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/google-protobuf-3.21.12-x86_64-darwin/lib/google/protobuf.rb:51:in `require'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/google-protobuf-3.21.12-x86_64-darwin/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/google-protobuf-3.21.12-x86_64-darwin/lib/google/protobuf.rb:48:in `<top (required)>'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/sass-embedded-1.57.1-x86_64-darwin/ext/sass/embedded_sass_pb.rb:4:in `require'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/sass-embedded-1.57.1-x86_64-darwin/ext/sass/embedded_sass_pb.rb:4:in `<top (required)>'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/sass-embedded-1.57.1-x86_64-darwin/lib/sass/embedded.rb:4:in `require_relative'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/sass-embedded-1.57.1-x86_64-darwin/lib/sass/embedded.rb:4:in `<top (required)>'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/sass-embedded-1.57.1-x86_64-darwin/lib/sass-embedded.rb:4:in `require_relative'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/sass-embedded-1.57.1-x86_64-darwin/lib/sass-embedded.rb:4:in `<top (required)>'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:8:in `require'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:8:in `<top (required)>'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll-sass-converter.rb:4:in `require'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.3.1/lib/jekyll.rb:195:in `require'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.3.1/lib/jekyll.rb:195:in `<top (required)>'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.3.1/exe/jekyll:8:in `require'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/gems/jekyll-4.3.1/exe/jekyll:8:in `<top (required)>'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `load'
  /Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `<top (required)>'
```

Please, can you kindly advise. 

Thank you.

**Comment by JugglerX** [comment]
Looks like some kind of issue with your environment. 

Probably related to this

```
bundler: failed to load command: jekyll (/Users/shmuhammad/Document/Git/myproject/jekyll-serif-theme/vendor/bundle/ruby/2.6.0/bin/jekyll)
LoadError: cannot load such file -- google/protobuf_c
```
